### ISSUE TITLE
incompatible types: CordovaWebView cannot be converted to View

### ISSUE THREAD

**Issue by moshemarom** [phonostar/PhoneGap-SoftKeyboard#9]
I'm using cordova version 5.3.3

Using the following commands to create new android project "demo":
cordova create demo

cd demo

cordova platform add android

cordova plugin add https://github.com/ti8m/DocumentHandler.git

cordova plugin add https://github.com/phonostar/PhoneGap-SoftKeyboard.git

cordova build android

**build failed:

C:\Users\demo\platforms\android\src\de\phonostar\SoftKeyboard.java:18: error: incompatible types: CordovaWebView cannot be converted to View mgr.showSoftInput(webView, InputMethodManager.SHOW_IMPLICIT);**
it works in version 4.3 and below,

using phonegap 5.3.6 gives the same error.

Please help,

Thanks

**Comment by sbruhns** [comment]
Please ignore the muliple commits releated to the issue. I used the github editor first time to quick edit and do some rebases and get no way to delete releated commits to the issue.

 d4d74a1 should be the correct.

**Comment by IlmanNurcahyanto** [comment]
. same
C:\Users\demo\platforms\android\src\de\phonostar\SoftKeyboard.java:18: error: incompatible types: CordovaWebView cannot be converted to View mgr.showSoftInput(webView, InputMethodManager.SHOW_IMPLICIT);**
it works in version 4.3 and below,
